version: '3.7'
services:
  app: 
    build:
      dockerfile: Dockerfile
      context: .
    # env_file: .env
    ports:
      - "8000:8000"
    environment:
      - APP
      - ENVIRONMENT
      - LOG_LEVEL
      - HTTP_PORT
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    # env_file: .env
    environment:
      POSTGRES_DB: recipe_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./deploy/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./migrations:/migrations
    command:  ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?sslmode=disable", "up"]



networks:
  default:
    external:
      name: test-network