version: '3.7'
services:
  app: 
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    networks:
      - default
    ports:
      - "8000:${HTTP_PORT}"
    environment:
      - APP
      - ENVIRONMENT
      - LOG_LEVEL
      - HTTP_PORT
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    env_file: .env
    networks:
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./deploy/pg_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./migrations:/migrations
    command:  ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?sslmode=disable", "up"]

networks:
  default:
    external:
      name: test-network